# Generated by Django 5.1.7 on 2025-03-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('service', '0002_service_description_service_price_service_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='servicio',
        ),
        migrations.AddField(
            model_name='citas',
            name='servicios',
            field=models.ManyToManyField(to='service.service'),
        ),
    ]
